Imported upstream version 3.99.pre4

diff --git a/src/avwutils/avwswapdim++ b/src/avwutils/avwswapdim++
--- a/src/avwutils/avwswapdim++
+++ b/src/avwutils/avwswapdim++
@@ -1,6 +1,11 @@
 #!/bin/sh
 
-#   Copyright (C) 2004 University of Oxford
+#   Extended syntax for fslswapdim
+#
+#   Mark Jenkinson
+#   FMRIB Image Analysis Group
+#
+#   Copyright (C) 2007 University of Oxford
 #
 #   Part of FSL - FMRIB's Software Library
 #   http://www.fmrib.ox.ac.uk/fsl
@@ -64,133 +69,77 @@
 #   University, to negotiate a licence. Contact details are:
 #   innovation@isis.ox.ac.uk quoting reference DE/1112.
 
-if [ "x$SGE_ROOT" = "x" ] ; then
-  if [ -f /usr/local/share/sge-6.0/default/common/settings.sh ] ; then
-    . /usr/local/share/sge-6.0/default/common/settings.sh
-  else if [ -f /usr/local/sge-6/default/common/settings.sh ] ; then
-      . /usr/local/sge-6/default/common/settings.sh
-    else
-      echo "bedpost: Couldn\'t locate SGE_ROOT\!"
-      exit 255
-    fi
-  fi
-fi
 
-Usage() {
-    echo ""
-    echo "Usage: bedpost <subject directory> "
-    echo ""
-    echo "expects to find bvals and bvecs in subject directory"
-    echo "expects to find data nodif_brain_mask nodif in subject directory"
-    echo ""
-    exit
-}
-
-make_absolute(){
-    dir=$1;
-    if [ -d ${dir} ]; then
-	OLDWD=`pwd`
-	cd ${dir}
-	dir_all=`pwd`
-	cd $OLDWD
-    else
-	dir_all=${dir}
-    fi
-    echo ${dir_all}
+get_axis(){
+    # search for either $1 or its reverse in $2 $3 $4
+    # e.g. get_axis RL AP SI LR would return -z (as $1 = $4 but backwards)
+    # whereas get_axis RL AP SI RL would return z (as $1 = $4)
+    ax="";
+    pre="";
+    k2=`echo $1 | tr RLAPSI LRPAIS`;
+    for fn in "$2:x" "$3:y" "$4:z" ; do
+	ff=`echo $fn | sed 's/:.*//'`;
+	aa=`echo $fn | sed 's/.*://'`;
+	if [ $ff = $1 ] ; then ax=$aa ; fi
+	if [ $ff = $k2 ] ; then ax=$aa ; pre="-" ; fi
+    done
+    ax="${pre}${ax}";
+    echo $ax;
 }
 
 
-[ "$1" = "" ] && Usage
+if [ $# -lt 4 ] ; then
+  echo "Usage: avwswapdim++ <input> <a> <b> <c> [output]
 
-subjdir=`make_absolute $1`
-subjdir=`echo $subjdir | sed 's/\/$/$/g'`
-
-echo subjectdir is $subjdir
-
-#check that all required files exist
-
-if [ ! -d $subjdir ]; then
-	echo "subject directory $1 not found"
+  where a,b,c represent the new x,y,z axes in terms of the
+  old axes.  They can take values of -x,x,y,-y,z,-z
+  or RL,LR,AP,PA,SI,IS (in the case of nifti inputs)
+  e.g.  avwswapdim++ invol y x -z outvol
+  or    avwswapdim++ invol RL PA IS outvol
+  where the latter will convert to axial slicing 
+  (to match the avg152 images)"
+  exit 1;
 fi
 
-if [ ! -e ${subjdir}/bvecs ]; then
-	echo "${subjdir}/bvecs not found"
+filetype=`$FSLDIR/bin/fslval $1 file_type`;
+if [ $filetype = "ANALYZE-7.5" ] ; then
+    nifti=no;
+else 
+    nifti=yes;
 fi
 
-if [ ! -e ${subjdir}/bvals ]; then
-	echo "${subjdir}/bvals not found"
-fi
-
-if [ `${FSLDIR}/bin/imtest ${subjdir}/data` -eq 0 ]; then
-	echo "${subjdir}/data not found"
-fi
-
-if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif` -eq 0 ]; then
-	echo "${subjdir}/nodif not found"
-fi
-
-if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif_brain_mask` -eq 0 ]; then
-	echo "${subjdir}/nodif_brain_mask not found"
-fi
-
-echo Making bedpost directory structure
-
-mkdir -p ${subjdir}.bedpost/
-mkdir -p ${subjdir}.bedpost/diff_slices
-mkdir -p ${subjdir}.bedpost/logs
-mkdir -p ${subjdir}.bedpost/logs/pid_${$}
-mkdir -p ${subjdir}.bedpost/xfms
-
-mailto=`whoami`@fmrib.ox.ac.uk
-
-echo Queuing preprocessing stages
-preprocid=`qsub -M $mailto -V -q short.q \
-    -o ${subjdir}.bedpost/logs -e ${subjdir}.bedpost/logs \
-    ${FSLDIR}/bin/bedpost_preproc.sh ${subjdir} | \
-    awk '{print $3}'`
-
-echo Queuing parallel processing stage
-nslices=`avwval ${subjdir}/data dim3`
-bedpostid=`qsub -M $mailto -hold_jid $preprocid -V -q long.q -t 1-$nslices \
-    -o ${subjdir}.bedpost/logs -e ${subjdir}.bedpost/logs \
-    ${FSLDIR}/bin/bedpost_single_slice.sh $subjdir | \
-    awk '{print $3}' | awk -F. '{print $1}'`
-
-echo Queuing post processing stage
-mergeid=`qsub -M $mailto -hold_jid $bedpostid -V -q short.q \
-    -o ${subjdir}.bedpost/logs -e ${subjdir}.bedpost/logs \
-    ${FSLDIR}/bin/bedpost_postproc.sh $subjdir | \
-    awk '{print $3}'`
-
-echo
-echo Type ${subjdir}.bedpost/monitor to show progress.
-cat <<EOM > ${subjdir}.bedpost/monitor
-#!/bin/sh
-finished=0
-logdir=${subjdir}.bedpost/logs
-while [ \$finished -eq 0 ] ; do
-    nfin=0
-    if [ -f \$logdir/bedpost.o$bedpostid.1 ] ; then
-      nfin=\`cat \$logdir/bedpost.o$bedpostid.* |\
-        grep Done | wc -w | awk '{print \$1}'\` 
+orient=yes;
+if [ $nifti = yes ] ; then
+    if [ `$FSLDIR/bin/fslval $1 sform_code` -gt 0 ] ; then
+	labs=`$FSLDIR/bin/fslhd $1 | grep sform_.orient | sed 's/[^A-Z]//g'`;
+    elif [ `$FSLDIR/bin/fslval $1 qform_code` -gt 0 ] ; then
+	labs=`$FSLDIR/bin/fslhd $1 | grep qform_.orient | sed 's/[^A-Z]//g'`;
+    else
+	labs="RL PA IS";  # default - but not safe
+	orient=no;
     fi
-    if [ \$nfin -eq $nslices ] ; then
-        finished=1
-    fi
+fi
 
-    echo "\$nfin slices processed"
-    sleep 600;
+comm="$FSLDIR/bin/fslswapdim $1"
+for fn in $2 $3 $4 ; do
+    cc=`echo Q$fn | sed 's/[RLAPIS]//g'`;
+    if [ $cc = "Q" ] ; then
+	if [ $nifti = no ] ; then
+	    echo "Cannot use RLAPSI notation for non-nifti files"
+	    exit 2
+	fi
+	if [ $orient = no ] ; then
+	    echo "Cannot use RLAPSI notation for nifti files without either sform or qform set"
+	    exit 2
+	fi
+	cc=`get_axis $fn $labs`;
+    else 
+	cc=$fn;
+    fi
+    comm="$comm $cc";
 done
-EOM
-chmod +x ${subjdir}.bedpost/monitor
 
-echo Type ${subjdir}.bedpost/cancel to terminate the task.
-cat <<EOC > ${subjdir}.bedpost/cancel
-#!/bin/sh
-qdel $mergeid $bedpostid $preprocid
-EOC
-chmod +x ${subjdir}.bedpost/cancel
+comm="$comm $5"
 
-echo
-echo You will get an email at the end of the post-processing stage.
-echo
+echo $comm
+
diff --git a/src/fdt/bedpostX b/src/fdt/bedpostX
--- a/src/fdt/bedpostX
+++ b/src/fdt/bedpostX
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+#   Copyright (C) 2004 University of Oxford
+#
 #   Part of FSL - FMRIB's Software Library
 #   http://www.fmrib.ox.ac.uk/fsl
 #   fsl@fmrib.ox.ac.uk
@@ -62,8 +64,12 @@
 #   University, to negotiate a licence. Contact details are:
 #   innovation@isis.ox.ac.uk quoting reference DE/1112.
 
-if [ "x$SGE_ROOT" != "x" ] && [ -f $FSLDIR/bin/sge_bedpostX ] ; then
-    exec $FSLDIR/bin/sge_bedpostX $@
+if [ "x$SGE_ROOT" = "x" ] ; then
+    if [ -f /usr/local/share/sge/default/common/settings.sh ] ; then
+	. /usr/local/share/sge/default/common/settings.sh
+    elif [ -f /usr/local/sge/default/common/settings.sh ] ; then
+	. /usr/local/sge/default/common/settings.sh
+    fi
 fi
 
 Usage() {
@@ -77,64 +83,7 @@ Usage() {
     echo "-w (ARD weight, more weight means less fibres killed per voxel, default 1)"
     echo "-b (burnin period, default 1000)"
     echo ""
-    exit
-}
-
-trap Clean_Exit 2
-
-
-Clean_Exit(){
-
-	if [ -d ${subjdir}.bedpostX/logs/pid_${$} ];then
-	    i=`ls  ${subjdir}.bedpostX/logs/pid_${$}`
-	    for j in ${i};do 
-		host=`echo $j | awk -F _fdt_ '{print $1}'`
-		pid=`echo $j | awk -F _fdt_ '{print $2}'`
-		if [ "x${FSLMACHINELIST}" != "x" ]; then
-#	            ${FSLREMOTECALL} $host "kill -KILL $pid" #this leaves one child process per processor - what can you do?
-		 echo "if [ -r /usr/local/etc/fslconf/fsl.sh ];then . /usr/local/etc/fslconf/fsl.sh;fi; if [ -r /etc/fslconf/fsl.sh ];then . /etc/fslconf/fsl.sh;fi; if [ -r \${HOME}/.fslconf/fsl.sh ]; then . \${HOME}/.fslconf/fsl.sh; fi; if [ x\${FSLDIR} != "x" ];then \${FSLDIR}/bin/bedpostX_kill_pid ${pid} >/dev/null 2>&1; else echo FSLDIR not set in any default location on machine `hostname`;fi" | $FSLREMOTECALL $host /bin/sh >/dev/null 2>&1 &
-		else
-		    ${FSLDIR}/bin/bedpostX_kill_pid ${pid}
-		fi
-		rm ${subjdir}.bedpostX/logs/pid_${$}/${j}
-	    done
-	fi
-	ExitUnlock;
-}
-
-Lock(){
-    if [ "x${FSLLOCKDIR}" != "x" ];then
-	touch ${FSLLOCKDIR}/.bedpostX.lock
-    fi
-}
-
-ExitUnlock(){
-    if [ -f ${FSLLOCKDIR}/.bedpostX.lock ];then
-	rm ${FSLLOCKDIR}/.bedpostX.lock
-    fi
-
-    #clean up slices
-    ndat_sl=`echo ${subjdir}/data_slice_* | grep -v "slice_\*" |wc -w` 
-    nnodif_sl=`echo ${subjdir}/nodif_brain_mask_slice_* | grep -v "slice_\*" |wc -w` 
-    if [ $ndat_sl -ge 0 ] ;then 
-	rm -f ${subjdir}/data_slice_*
-    fi
-    
-    if [ $nnodif_sl -ge 0 ] ;then 
-	rm -f ${subjdir}/nodif_brain_mask_slice_*
-    fi
-    
-    exit
-}
-
-LockTest(){
-    if [ "x${FSLLOCKDIR}" = "x" ];then
-	echo 1;
-    elif [ ! -f ${FSLLOCKDIR}/.bedpostX.lock ];then
-	echo 1;
-    else
-	echo 0;
-    fi
+    exit 1
 }
 
 make_absolute(){
@@ -150,63 +99,12 @@ make_absolute(){
     echo ${dir_all}
 }
 
-
-
 [ "$1" = "" ] && Usage
-
-if [ `LockTest` -eq 0 ]; then
-    echo "bedpostX is currently being run - try again later"
-    exit
-fi
-
-if [ "x${FSLMACHINELIST}" != "x" ];then
-    if [ "x${FSLREMOTECALL}" = "x" ];then
-	echo "error: you must set FSLREMOTECALL if you have set FSLMACHINELIST"
-	exit
-    fi
-fi
-
-Lock;
-
 
 subjdir=`make_absolute $1`
 subjdir=`echo $subjdir | sed 's/\/$/$/g'`
 
 echo subjectdir is $subjdir
-
-#check that all required files exist
-
-
-if [ ! -d $subjdir ]; then
-	echo "subject directory $1 not found"
-	ExitUnlock
-fi
-
-if [ ! -f ${subjdir}/bvecs ]; then
-	echo "${subjdir}/bvecs not found"
-	ExitUnlock
-fi
-
-if [ ! -f ${subjdir}/bvals ]; then
-	echo "${subjdir}/bvals not found"
-	ExitUnlock
-fi
-
-if [ `${FSLDIR}/bin/imtest ${subjdir}/data` -eq 0 ]; then
-	echo "${subjdir}/data not found"
-	ExitUnlock
-fi
-
-if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif` -eq 0 ]; then
-	echo "${subjdir}/nodif not found"
-	ExitUnlock
-fi
-
-if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif_brain_mask` -eq 0 ]; then
-	echo "${subjdir}/nodif_brain_mask not found"
-	ExitUnlock
-fi
-
 
 #parse option arguments
 nfibres=2
@@ -223,102 +121,93 @@ do
   shift
 done
 
+#check that all required files exist
 
-echo making bedpostX directory
+if [ ! -d $subjdir ]; then
+	echo "subject directory $1 not found"
+	exit 1
+fi
+
+if [ ! -e ${subjdir}/bvecs ]; then
+	echo "${subjdir}/bvecs not found"
+	exit 1
+fi
+
+if [ ! -e ${subjdir}/bvals ]; then
+	echo "${subjdir}/bvals not found"
+	exit 1
+fi
+
+if [ `${FSLDIR}/bin/imtest ${subjdir}/data` -eq 0 ]; then
+	echo "${subjdir}/data not found"
+	exit 1
+fi
+
+if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif` -eq 0 ]; then
+	echo "${subjdir}/nodif not found"
+	exit 1
+fi
+
+if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif_brain_mask` -eq 0 ]; then
+	echo "${subjdir}/nodif_brain_mask not found"
+	exit 1
+fi
+
+echo Making bedpostX directory structure
+
 mkdir -p ${subjdir}.bedpostX/
 mkdir -p ${subjdir}.bedpostX/diff_slices
-
-echo copying files to bedpostX directory
-cp ${subjdir}/bvecs ${subjdir}/bvals ${subjdir}.bedpostX
-${FSLDIR}/bin/imcp ${subjdir}/nodif ${subjdir}/nodif_brain_mask ${subjdir}.bedpostX
-${FSLDIR}/bin/avwmaths ${subjdir}/nodif -mas ${subjdir}/nodif_brain_mask ${subjdir}.bedpostX/nodif_brain
-
-
 mkdir -p ${subjdir}.bedpostX/logs
 mkdir -p ${subjdir}.bedpostX/logs/pid_${$}
+mkdir -p ${subjdir}.bedpostX/xfms
 
+mailto=`whoami`@fmrib.ox.ac.uk
+echo Queuing preprocessing stages
+preprocid=`${FSLDIR}/bin/fsl_sub -F -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostX_preproc.sh ${subjdir}`
+
+echo Queuing parallel processing stage
 nslices=`${FSLDIR}/bin/avwval ${subjdir}/data dim3`
-
-${FSLDIR}/bin/avwslice ${subjdir}/data
-${FSLDIR}/bin/avwslice ${subjdir}/nodif_brain_mask
-
-#for parallel processing, the following need to be setup elsewhere
-#FSLMACHINELIST="list of machines (can be duplicated for two processors etc.)"
-#FSLREMOTECALL="ssh (or rsh or whatever you want to use)"
-
-if [ "x$FSLMACHINELIST" = "x" ] ; then
-    echo "processing data on local host"
-    ${FSLDIR}/bin/bedpostX_proc $subjdir $nslices -n $nfibres -w $fudge -b $burnin ${subjdir}.bedpostX/logs/pid_${$} &
-else
-    echo "processing data on hosts: $FSLMACHINELIST"
-    for machine in $FSLMACHINELIST; do
-	echo "if [ -r /usr/local/etc/fslconf/fsl.sh ];then . /usr/local/etc/fslconf/fsl.sh;fi; if [ -r /etc/fslconf/fsl.sh ];then . /etc/fslconf/fsl.sh;fi; if [ -r \${HOME}/.fslconf/fsl.sh ]; then . \${HOME}/.fslconf/fsl.sh; fi; if [ x\${FSLDIR} != "x" ];then \${FSLDIR}/bin/bedpostX_proc $subjdir $nslices ${subjdir}.bedpostX/logs/pid_${$}; else echo FSLDIR not set in any default location on machine `hostname`;fi"|	$FSLREMOTECALL $machine /bin/sh  &
-    done
-fi
-echo finished
-
-b=0
-finished=0;
-while [ $finished -eq 0 ];do
-    b=`expr $b + 1 `
-    sleep 60;
-    nfin=`echo ${subjdir}.bedpostX/logs/.*_finished | grep -v ".\*" |wc -w` 
-    if [ $nfin -eq $nslices ];then
-	finished=1;
-    fi
-    if [ $b -eq 10 ]; then 
-	echo "$nfin slices processed"
-	b=0
-    fi	
+[ -f ${subjdir}.bedpostX/commands.txt ] && rm ${subjdir}.bedpostX/commands.txt
+for ((slice=0; slice < $nslices; slice++)) ; do
+    echo "${FSLDIR}/bin/bedpostX_single_slice.sh $subjdir $nfibres $fudge $burnin $slice" \
+	>> ${subjdir}.bedpostX/commands.txt
 done
+bedpostid=`${FSLDIR}/bin/fsl_sub -j $preprocid -l ${subjdir}.bedpostX/logs -M $mailto -N bedpostx -t ${subjdir}.bedpostX/commands.txt`
 
-#postprocessing
-#postprocess $subjdir
+echo Queuing post processing stage
+mergeid=`${FSLDIR}/bin/fsl_sub -j $bedpostid -F -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostX_postproc.sh $subjdir`
 
-
-numfib=`${FSLDIR}/bin/imglob -oneperimage ${subjdir}.bedpostX/diff_slices/data_slice_0000/f*samples |wc -w`
-echo number of fibres $numfib
-
-fib=1;
-while [ $fib -le $numfib ];do
-    ${FSLDIR}/bin/avwmerge -z ${subjdir}.bedpostX/merged_th${fib}samples `${FSLDIR}/bin/imglob -oneperimage ${subjdir}.bedpostX/diff_slices/data_slice_*/th${fib}samples`
-    ${FSLDIR}/bin/avwmerge -z ${subjdir}.bedpostX/merged_ph${fib}samples `${FSLDIR}/bin/imglob -oneperimage ${subjdir}.bedpostX/diff_slices/data_slice_*/ph${fib}samples`
-    ${FSLDIR}/bin/avwmerge -z ${subjdir}.bedpostX/merged_f${fib}samples  `${FSLDIR}/bin/imglob -oneperimage ${subjdir}.bedpostX/diff_slices/data_slice_*/f${fib}samples`
-    ${FSLDIR}/bin/avwmaths ${subjdir}.bedpostX/merged_th${fib}samples -Tmean ${subjdir}.bedpostX/mean_th${fib}samples
-    ${FSLDIR}/bin/avwmaths ${subjdir}.bedpostX/merged_ph${fib}samples -Tmean ${subjdir}.bedpostX/mean_ph${fib}samples
-    ${FSLDIR}/bin/avwmaths ${subjdir}.bedpostX/merged_f${fib}samples -Tmean ${subjdir}.bedpostX/mean_f${fib}samples
-
-    ${FSLDIR}/bin/make_dyadic_vectors ${subjdir}.bedpostX/merged_th${fib}samples ${subjdir}.bedpostX/merged_ph${fib}samples ${subjdir}.bedpostX/nodif_brain_mask ${subjdir}.bedpostX/dyads${fib}
-
-    fib=`echo "$fib +1"|bc`;
-done
-
-echo Removing intermediate files
-
-if [ `imtest ${subjdir}.bedpostX/merged_th1samples` -eq 1 ];then
-  if [ `imtest ${subjdir}.bedpostX/merged_ph1samples` -eq 1 ];then
-    if [ `imtest ${subjdir}.bedpostX/merged_f1samples` -eq 1 ];then
-      rm -rf ${subjdir}.bedpostX/diff_slices
-      rm -f ${subjdir}/data_slice_*
-      rm -f ${subjdir}/nodif_brain_mask_slice_*
+if [ "x$SGE_ROOT" != "x" ]; then
+    echo
+    echo Type ${subjdir}.bedpostX/monitor to show progress.
+    cat <<EOM > ${subjdir}.bedpostX/monitor
+#!/bin/sh
+finished=0
+logdir=${subjdir}.bedpostX/logs
+while [ \$finished -eq 0 ] ; do
+    nfin=0
+    if [ -f \$logdir/bedpost.o$bedpostid.1 ] ; then
+      nfin=\`cat \$logdir/bedpostx.o$bedpostid.* |\
+        grep Done | wc -w | awk '{print \$1}'\` 
     fi
-  fi
+    if [ \$nfin -eq $nslices ] ; then
+        finished=1
+    fi
+
+    echo "\$nfin slices processed"
+    sleep 600;
+done
+EOM
+    chmod +x ${subjdir}.bedpostX/monitor
+
+    echo Type ${subjdir}.bedpostX/cancel to terminate all the queued tasks.
+    cat <<EOC > ${subjdir}.bedpostX/cancel
+#!/bin/sh
+qdel $mergeid $bedpostid $preprocid
+EOC
+    chmod +x ${subjdir}.bedpostX/cancel
+
+    echo
+    echo You will get an email at the end of the post-processing stage.
+    echo
 fi
-
-echo Creating identity xfm
-
-xfmdir=${subjdir}.bedpostX/xfms
-mkdir -p $xfmdir
-echo 1 0 0 0 > ${xfmdir}/eye.mat
-echo 0 1 0 0 >> ${xfmdir}/eye.mat
-echo 0 0 1 0 >> ${xfmdir}/eye.mat
-echo 0 0 0 1 >> ${xfmdir}/eye.mat
-
-echo Done
-
-ExitUnlock
-
-
-
-
-
